services:
  - type: web
    name: kobra-game-server
    env: node
    plan: starter
    buildCommand: cd apps/server && npm install --include=dev && npx tsc
    startCommand: cd apps/server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
